-- java
INSERT INTO questions (id, question, option1, option2, option3, option4, correct_answers, is_multiple_choice, category) VALUES
(1, 'How many pillars of OOPs java has?', '3', '4', '5', '6', '2', false, 'java'),
(2, 'What is the default value of a boolean variable in Java?', 'True', 'False', 'Null', '0', '2', false, 'java'),
(3, 'Which of the following is not a valid data type in Java?', 'int', 'float', 'double', 'real', '3', false, 'java'),
(4, 'What is the main purpose of the final keyword in Java?', 'To declare a constant', 'To prevent method overriding', 'To prevent inheritance', 'All of the above', '3', false, 'java'),
(5, 'Which of the following methods can be used to start a thread in Java?', 'run()', 'start()', 'execute()', 'begin()', '1', false, 'java'),
(6, 'Output: int x = 10; int y = 20; System.out.println(x + y + "10");', '3010', '2010', '30', '210', '0', false, 'java'),
(7, 'What is the main entry point of a Java application?', 'main()', 'start()', 'init()', 'run()', '0', false, 'java'),
(8, 'Which keyword is used to create a class in Java?', 'class', 'create', 'new', 'define', '0', false, 'java'),
(9, 'Which of the following are primitive data types in Java?', 'int', 'String', 'boolean', 'char', '0,2,3', true, 'java'),
(10, 'Which of the following are valid keywords in Java?', 'static', 'void', 'main', 'function', '0,1,2', true, 'java'),
(11, 'Which of the following are valid ways to create an object in Java?', 'Using new keyword', 'Using factory methods', 'Using cloning', 'Using constructors', '0,1,3', true, 'java'),
(12, 'Which of the following can be used to handle exceptions in Java?', 'try-catch', 'throw', 'throws', 'finally', '0,1,2,3', true, 'java'),
(13, 'Which of the following are features of Java?', 'Platform independence', 'Object-oriented', 'Automatic garbage collection', 'Pointer arithmetic', '0,1,2', true, 'java'),
(14, 'Which of the following are types of loops in Java?', 'for', 'while', 'do-while', 'foreach', '0,1,2,3', true, 'java'),
(15, 'Which of the following are collection interfaces in Java?', 'List', 'Set', 'Map', 'Array', '0,1,2', true, 'java'),
(16, 'Which of the following access modifiers are available in Java?', 'public', 'private', 'protected', 'friend', '0,1,2', true, 'java'),
(17, 'Which of the following are valid ways to declare an array in Java?', 'int[] arr;', 'int arr[];', 'int arr = new int[5];', 'int[] arr = new int[];', '0,1,2', true, 'java'),
(18, 'Which of the following statements about interfaces are true?', 'Interfaces can extend other interfaces', 'An interface can contain method implementations', 'A class can implement multiple interfaces', 'Interfaces cannot have instance variables', '0,2,3', true, 'java'),
(19, 'Which of the following are valid Java annotations?', '@Override', '@Entity', '@Service', '@Main', '0,1,2', true, 'java'),
(20, 'Which of the following are valid ways to implement a thread in Java?', 'Extending Thread class', 'Implementing Runnable interface', 'Using ExecutorService', 'Creating a method', '0,1,2', true, 'java'),
(21, 'Which of the following statements about the Java Collections Framework are true?', 'It provides data structures for storing groups of objects', 'It supports sorting and searching operations', 'All collections implement the Collection interface', 'Collections can be synchronized', '0,1,2,3', true, 'java'),
(22, 'Which of the following are valid Java stream operations?', 'filter()', 'map()', 'reduce()', 'collect()', '0,1,2,3', true, 'java'),
(23, 'Which of the following are commonly used Java frameworks?', 'Spring', 'Hibernate', 'JSF', 'Angular', '0,1,2', true, 'java'),
(24, 'Which of the following statements about Java inheritance are true?', 'Java supports multiple inheritance', 'A class can only extend one class', 'Subclasses can override methods of superclasses', 'Constructors are inherited', '1,2', true, 'java'),
(25, 'Which of the following are valid types of exceptions in Java?', 'Checked exceptions', 'Unchecked exceptions', 'Errors', 'Runtime exceptions', '0,1,2,3', true, 'java'),
(26, 'Which of the following statements about Java memory management are true?', 'Memory allocation is done at runtime', 'Garbage collector automatically deallocates memory', 'Memory leaks can occur', 'Finalizers can be used to clean up resources', '0,1,2,3', true, 'java'),
(27, 'Which of the following are types of Java applications?', 'Standalone applications', 'Web applications', 'Mobile applications', 'Console applications', '0,1,2,3', true, 'java'),
(28, 'What does JVM stand for?', 'Java Variable Machine', 'Java Virtual Machine', 'Java Visual Machine', 'Java Value Machine', '1', false, 'java'),
(29, 'Which of the following is a valid way to declare an array in Java?', 'int[] arr;', 'int arr[];', 'Both 1 and 2', 'None of the above', '2', false, 'java'),
(30, 'What is the default value of a boolean in Java?', 'true', 'false', '0', '1', '1', false, 'java'),
(31, 'Which of the following is not a valid access modifier in Java?', 'public', 'protected', 'private', 'internal', '3', false, 'java'),
(32, 'What does the \'static\' keyword indicate in Java?', 'Instance variable', 'Class variable', 'Local variable', 'Global variable', '1', false, 'java'),
(33, 'Which of the following can throw an exception in Java?', 'Runtime', 'Checked', 'Unchecked', 'All of the above', '3', false, 'java'),
(34, 'What is the purpose of the \'this\' keyword in Java?', 'To refer to the current instance', 'To call a constructor', 'To access static members', 'None of the above', '0', false, 'java'),
(35, 'Which method is used to compare two strings in Java?', 'compare()', 'equals()', '==', 'compareTo()', '1', false, 'java'),
(36, 'What is the output of \'System.out.println(1 + 2 + "3");\'?', '33', '6', '15', 'Error', '1', false, 'java'),
(37, 'Which of the following is a valid constructor in Java?', 'ClassName()', 'void ClassName()', 'ClassName;', 'new ClassName()', '0', false, 'java'),
(38, 'What does the \'final\' keyword do in Java?', 'Makes a variable constant', 'Prevents method overriding', 'Prevents inheritance', 'All of the above', '3', false, 'java'),
(39, 'What is the size of an int in Java?', '2 bytes', '4 bytes', '8 bytes', '16 bytes', '1', false, 'java'),
(40, 'Which of the following collections is ordered in Java?', 'HashSet', 'TreeSet', 'ArrayList', 'HashMap', '2', false, 'java'),
(41, 'What is a Java package?', 'A collection of classes', 'A way to organize classes', 'Both 1 and 2', 'None of the above', '2', false, 'java'),
(42, 'Which of the following is used to create a thread in Java?', 'Runnable', 'Thread', 'Both 1 and 2', 'Process', '2', false, 'java'),
(43, 'What does the \'super\' keyword do in Java?', 'Access parent class methods', 'Call a superclass constructor', 'Both 1 and 2', 'None of the above', '2', false, 'java'),
(44, 'Which annotation is used to mark a method as an override in Java?', '@Override', '@OverrideMethod', '@OverrideFunc', '@Super', '0', false, 'java'),
(45, 'What does the term \'polymorphism\' refer to in Java?', 'Multiple forms of methods', 'Overloading methods', 'Overriding methods', 'All of the above', '3', false, 'java'),
(46, 'What is a lambda expression in Java?', 'A way to define anonymous functions', 'A new data type', 'An exception', 'None of the above', '0', false, 'java'),
(47, 'Which of the following is not a primitive data type in Java?', 'int', 'float', 'String', 'boolean', '2', false, 'java'),
(48, 'What is the main purpose of the \'try-catch\' block in Java?', 'To handle exceptions', 'To define a loop', 'To create threads', 'None of the above', '0', false, 'java'),
(49, 'Which of the following interfaces allows you to iterate over a collection in Java?', 'Iterable', 'Collection', 'Iterator', 'All of the above', '3', false, 'java'),
(50, 'Which framework is commonly used for building web applications in Java?', 'Spring', 'Hibernate', 'Struts', 'All of the above', '3', false, 'java'),
(51, 'What is the purpose of the \'jdbc\' in Java?', 'Java Database Connectivity', 'Java Data Connection', 'Java Data Control', 'None of the above', '0', false, 'java'),
(52, 'What is the default scope of a bean in Spring?', 'Singleton', 'Prototype', 'Request', 'Session', '0', false, 'java'),
(53, 'Which of the following is a NoSQL database?', 'MySQL', 'PostgreSQL', 'MongoDB', 'Oracle', '2', false, 'java'),
(54, 'What is REST in web services?', 'Representational State Transfer', 'Remote State Transfer', 'Real-time State Transfer', 'None of the above', '0', false, 'java'),
(55, 'What does the \'@RequestMapping\' annotation do in Spring?', 'Maps HTTP requests to handler methods', 'Defines a service', 'Creates a bean', 'None of the above', '0', false, 'java'),
(56, 'What is the primary purpose of the Model-View-Controller (MVC) pattern?', 'Separation of concerns', 'Database management', 'Client-server architecture', 'None of the above', '0', false, 'java'),
(57, 'Which of the following is a Java build tool?', 'Maven', 'Gradle', 'Ant', 'All of the above', '3', false, 'java'),
(58, 'What is the function of \'application.properties\' in a Spring Boot application?', 'Configuration settings', 'Database settings', 'Environment variables', 'None of the above', '0', false, 'java'),
(59, 'What is the purpose of the \'pom.xml\' file in Maven?', 'Project configuration', 'Dependency management', 'Build instructions', 'All of the above', '3', false, 'java'),
(60, 'Which of the following is used to perform dependency injection in Spring?', '@Autowired', '@Inject', '@Component', 'All of the above', '3', false, 'java'),
(61, 'What is the purpose of \'docker\' in full-stack development?', 'Containerization', 'Database management', 'Web server management', 'None of the above', '0', false, 'java'),
(62, 'What is the primary language used for Android development?', 'Kotlin', 'Java', 'C++', 'Swift', '1', false, 'java'),
(63, 'What is the purpose of \'JSON\' in web applications?', 'Data interchange format', 'Database management', 'Web server communication', 'None of the above', '0', false, 'java'),
(64, 'Which of the following is a popular front-end framework?', 'Angular', 'Spring', 'Hibernate', 'Maven', '0', false, 'java'),
(65, 'What is \'JPA\' used for in Java?', 'Java Persistence API', 'Java Process API', 'Java Performance API', 'None of the above', '0', false, 'java'),
(66, 'What is the function of \'Spring Security\'?', 'Authentication and authorization', 'Data validation', 'Web scraping', 'None of the above', '0', false, 'java'),
(67, 'Which of the following is an example of a relational database?', 'MySQL', 'MongoDB', 'Redis', 'Cassandra', '0', false, 'java'),
(68, 'What is the purpose of \'CORS\' in web applications?', 'Cross-Origin Resource Sharing', 'Content-Object Resource Sharing', 'Cross-Origin Redirect Sharing', 'None of the above', '0', false, 'java'),
(69, 'What is \'Spring Boot\' primarily used for?', 'Rapid application development', 'Database management', 'Web server configuration', 'None of the above', '0', false, 'java'),
(70, 'What is the superclass of all classes in Java?', 'Object', 'Class', 'Main', 'String', '0', false, 'java'),
(71, 'What is the purpose of the static keyword in Java?', 'To define a variable that belongs to the class', 'To define a method that can be called without creating an instance', 'To allocate memory for a variable at compile time', 'All of the above', '3', false, 'java'),
(72, 'Which of the following is used to prevent a method from being overridden in Java?', 'static', 'final', 'abstract', 'private', '1', false, 'java'),
(73, 'Which of the following is the correct way to declare an array in Java?', 'int arr[] = new int[5];', 'int arr = new int[5];', 'int[] arr = int[5];', 'array int arr = new int[5];', '0', false, 'java');

-- ccna
INSERT INTO ccna_questions (id, correct_answers, is_multiple_choice, option1, option2, option3, option4, question, category) VALUES
(75, '1', '0', 'Forward packets within a local network', 'Route packets between different networks', 'Filter malicious traffic', 'Convert IP addresses to MAC addresses', 'What is the primary function of a router in a network?', 'ccna'),
(76, '1', '0', 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 7', 'Which layer of the OSI model do routers primarily operate on?', 'ccna'),
(77, '1', '0', 'Layer 2 switches operate on IP addresses, Layer 3 switches operate on MAC addresses', 'Layer 2 switches operate on MAC addresses, Layer 3 switches operate on IP addresses', 'Layer 2 switches use VLANs, Layer 3 switches do not', 'Layer 3 switches are slower than Layer 2 switches', 'What is the primary difference between a Layer 2 and a Layer 3 switch?', 'ccna'),
(78, '1', '0', 'Switching only within VLANs', 'Routing between VLANs', 'ARP resolution', 'Firewall capabilities', 'Which of the following is a feature of Layer 3 switches?', 'ccna'),
(79, '1', '0', 'To forward packets between networks', 'To provide services to client devices', 'To route IP packets', 'To control switches', 'What is the primary function of a server in a network?', 'ccna'),
(80, '2', '0', 'Web hosting', 'Email hosting', 'Routing packets', 'Database management', 'Which of the following is NOT typically a role of a server?', 'ccna'),
(81, '1', '0', 'A device that provides network services', 'A device that initiates or receives network communication', 'A device that routes traffic', 'A wireless router', 'What is an endpoint in networking?', 'ccna'),
(82, '0', '0', 'Provides wireless signal coverage', 'Routes traffic between subnets', 'Converts analog signals to digital', 'Assigns IP addresses to clients', 'What does an access point do in a wireless network?', 'ccna'),
(83, '2', '0', '64 bits', '128 bits', '32 bits', '16 bits', 'What is the length of an IPv4 address?', 'ccna'),
(84, '1', '0', '16', '32', '64', '128', 'How many hexadecimal digits are there in an IPv6 address?', 'ccna'),
(85, '1', '0', 'Routing packets between different networks', 'Forwarding frames within a network based on MAC addresses', 'Translating domain names to IP addresses', 'Forwarding data based on IP addresses', 'What is switching in a network?', 'ccna'),
(86, '0', '0', 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 5', 'In which layer of the OSI model does switching occur?', 'ccna'),
(87, '1', '0', 'Virtual Link Access Node', 'Virtual Local Area Network', 'Virtual Logical Access Network', 'Virtual Layer Access Node', 'What does VLAN stand for?', 'ccna'),
(88, '0', '0', 'To isolate network traffic within the same physical network', 'To route packets between networks', 'To manage wireless access points', 'To assign IP addresses to devices', 'What is the primary purpose of a VLAN?', 'ccna'),
(89, '1', '0', 'To route traffic between VLANs', 'To prevent loops in a network', 'To assign IP addresses', 'To improve wireless signal strength', 'What is the purpose of the Spanning Tree Protocol (STP)?', 'ccna'),
(90, '0', '0', 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 7', 'STP operates at which OSI layer?', 'ccna'),
(91, '1', '0', 'Wide Local Area Network', 'Wireless Local Area Network', 'Wired Local Access Network', 'Wireless Layer Access Network', 'What does WLAN stand for?', 'ccna'),
(92, '0', '0', '2.4 GHz and 5 GHz', '1.2 GHz and 6 GHz', '3.1 GHz and 4.9 GHz', '7.2 GHz and 9 GHz', 'What frequency bands do WLANs typically operate on?', 'ccna'),
(93, '1', '0', 'MAC address', 'IP address', 'Domain name', 'URL', 'A router uses which of the following to make forwarding decisions?', 'ccna'),
(94, '2', '0', 'BGP', 'RIP', 'OSPF', 'SMTP', 'Which routing protocol is commonly used within autonomous systems?', 'ccna'),
(95, '1', '0', 'A route learned automatically by a router', 'A route manually configured by an administrator', 'A route used only for wireless traffic', 'A temporary route', 'What is a static route?', 'ccna'),
(96, '1', '0', 'It is not secure', 'It does not adapt to network changes', 'It is expensive', 'It requires IPv6', 'What is the primary disadvantage of static routing?', 'ccna'),
(97, '1', '0', 'A default route used by a router', 'A backup static route with a higher administrative distance', 'A dynamic route that adapts to changes', 'A temporary route used in wireless networks', 'What is a floating static route?', 'ccna'),
(98, '0', '0', 'When the primary route fails', 'When the network is congested', 'When a device sends a ping request', 'When the router is restarted', 'When does a floating static route become active?', 'ccna'),
(99, '1', '0', 'To assign IP addresses to devices', 'To forward packets to external networks', 'To resolve domain names', 'To provide encryption for wireless traffic', 'What is the function of a default gateway?', 'ccna'),
(100, '1', '0', 'To provide domain name resolution', 'To assign IP addresses automatically', 'To encrypt data traffic', 'To route packets between networks', 'What is the purpose of DHCP in a network?', 'ccna'),
(101, '3', '0', 'By subnet masks', 'By IP addresses', 'By MAC addresses', 'By logical segmentation', 'How is traffic separated in VLANs?', 'ccna'),
(102, '1', '0', 'VTP', '802.1Q', 'RIP', 'BGP', 'Which protocol is used to carry VLAN information over trunk links?', 'ccna'),
(103, '1', '0', 'Public IP address', 'Private IP address', 'Multicast address', 'Loopback address', 'What type of address is \'192.168.1.1\'?', 'ccna'),
(104, '2', '0', '32', '64', '128', '256', 'How many bits are there in an IPv6 address?', 'ccna'),
(105, '2', '0', 'IP address conflicts', 'VLAN segmentation', 'Broadcast storms', 'Domain name resolution issues', 'What does STP prevent in a switched network?', 'ccna'),
(106, '0', '0', 'Rapid STP (RSTP)', 'Basic STP', 'PortFast', 'Layer 3 STP', 'Which type of STP is most commonly used in modern networks?', 'ccna'),
(107, '3', '0', 'WEP', 'WPA', 'WPA2', 'WPA3', 'Which security protocol is considered the most secure for WLANs?', 'ccna'),
(108, '0', '0', 'Service Set Identifier', 'Security Signal Identification', 'Standard Signal Identification', 'Service Signal Identifier', 'What does SSID stand for in WLANs?', 'ccna'),
(109, '1', '0', 'OSPF', 'BGP', 'EIGRP', 'RIP', 'Which protocol is used to exchange routing information between different autonomous systems?', 'ccna'),
(110, '0', '0', '0', '1', '10', '20', 'What is the administrative distance of a directly connected route?', 'ccna'),
(111, '1', '0', 'A single VLAN used across multiple switches', 'A connection that carries multiple VLANs', 'A default VLAN used for management', 'A protocol for routing VLAN traffic', 'What is a VLAN trunk?', 'ccna'),
(112, '2', '0', '100', '256', '4096', '8192', 'What is the maximum number of VLANs supported on a switch?', 'ccna'),
(113, '0', '0', 'Application layer', 'Transport layer', 'Network layer', 'Data link layer', 'Which layer of the OSI model deals with encryption and compression?', 'ccna');
