-- A+ Questions
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('Which memory is known as volatile memory', 'RAM', 'ROM', 'EPROM', 'DVD', 0, 'hardware', 0),
('RAM stands for', 'Random Access Memory', 'Read Access Memory', 'Read Arithmetic Memory', 'Random Arithmetic Memory', 0, 'hardware', 0),
('The Central Processing Unit consists of', 'Control Unit', 'ALU', 'All the above', 'None of the above', 2, 'hardware', 0),
('Motherboard also known as', 'PCB', 'main circuit board', 'logic board', 'All the above', 3, 'hardware', 0),
('GPU stands for __?', 'Graphics Processing Unit', 'Game Processing Unit', 'Graphics Programming Unit', 'Graphics Problematic Unit', 0, 'hardware', 0),
('ROM stands for ___?', 'Random Only Memory', 'Read Only Memory', 'Rewrite only Memory', 'Review Only Memory', 1, 'hardware', 0),
('ROM categories __ Types.', '2', '3', '4', '5', 2, 'hardware', 0),
('The hardware device commonly referred to as the “brain” of the computer', 'Secondary storage', 'CPU', 'ROM', 'RAM Chip', 1, 'hardware', 0),
('Devices which are used to receive data from central processing unit are classified as', 'output/input devices', 'digital devices', 'signaled devices', 'output devices', 3, 'hardware', 0),
('The disks stores information in', 'Blocks', 'Tables', 'Tracks and sectors', 'Rows and columns', 2, 'hardware', 0),
('How many pins on a VGA?', '5', '15', '17', '21', 1, 'hardware', 0),
('In ROM BIOS, the acronym BIOS stands for:', 'Basic Intuitive Output Set', 'Basic Input Organizational System', 'Basic Input Output System', 'Basic Industry Operating System', 2, 'hardware', 0),
('Which common bus specification provides the fastest data transfer rate?', 'VL bus', 'ISA', 'PCI', 'None of the above', 2, 'hardware', 0),
('What is modified when changing the system start-up boot sequence?', 'BIOS/CMOS', 'CONFIG.SYS', 'autoexec.bat', 'COMMAND.COM', 0, 'hardware', 0),
('During the boot process, a system first counts memory from where?', 'Expansion memory board', 'Video adapter', 'System board', 'Cache', 2, 'hardware', 0),
('You suspect a virus has entered your computer. What will not be affected by the virus?', 'CMOS', 'Boot sector', 'Floppy disks', 'Program files', 0, 'hardware', 0),
('Which type of system board is the MOST likely candidate for processor upgrading if you want maximum performance and future compatibility?', 'PCI', 'ISA', 'EISA', 'ML', 0, 'hardware', 0),
('What can you use to ensure power is not interrupted, resulting in corrupted data?', 'UPS', 'Proper grounding', 'Surge protector', 'Nuclear powered thermal protection', 0, 'hardware', 0),
('The POST routine, what is POST stands ___?', 'Power on Self-Test', 'Power on Start Time', 'Process on Self-Test', 'Process on Start Time', 0, 'hardware', 0),
('The POST routine, which counts system board RAM first, is stored in', 'RAM', 'Microprocessor', 'ROM BIOS', 'CMOS', 2, 'hardware', 0),
('CMOS Stands for ___?', 'Common Metal Oxide Semiconductor', 'Complementary Metal Oxide Semiconductor', 'Complementary Meth Oxide Semiconductor', 'Common Metal Oxide Setting', 1, 'hardware', 0),
('Which among following can be considered as most advanced ROM?', 'DRAM', 'EEPROM', 'PROM', 'ROM', 1, 'hardware', 0),
('What device protects against line deficiencies?', 'Surge protector', 'transistor', 'UPS', 'Capacitor', 2, 'hardware', 0),
('What is full name of AMD?', 'Advanced Micro Devices', 'Automated Micro Devices', 'Advanced Mini Devices', 'None of these', 0, 'hardware', 0),
('During the normal PC boot process, which of the following is active first?', 'CMOS', 'RAM BIOS', 'ROM BIOS', 'Peripheral Devices like Mouse, keyboard', 2, 'hardware', 0),
('Which provides the fastest data access time?', 'RAM', 'ROM', 'CD-ROM', 'Hard disk', 0, 'hardware', 0),
('A hard disk is divided into tracks which are further subdivided into:', 'Clusters', 'Sectors', 'Vectors', 'Heads', 1, 'hardware', 0),
('All Operating Systems get their total memory initialized from?', 'CPU', 'ROM', 'RAM', 'BIOS', 2, 'hardware', 0),
('What device prevents power interruptions, resulting in corrupted data?', 'Battery back-up unit', 'Surge protector', 'Multiple SIMMs strips', 'Data guard system', 0, 'hardware', 0),
('With respect to a network interface card, the term 10/100 refers to', 'Megabits per seconds', 'Protocol speed', 'A fiber speed', 'Minimum and maximum server speed', 0, 'hardware', 0),
('Which of the following is not an input device?', 'VDU', 'Keyboard', 'Monitor', 'Light Pen', 2, 'hardware', 0),
('A light-sensitive device that converts printed text, drawing, or other images into digital form is called ____.', 'Plotter', 'Printer', 'Scanner', 'OMR', 2, 'hardware', 0),
('Information travels between components to Motherboard through?', 'CMOS', 'Busses', 'Bays', 'Flash memory', 1, 'hardware', 0),
('The resolution of Laser Printers is specified in terms of?', 'CPM', 'PPM', 'DPI', 'LPM', 2, 'hardware', 0),
('A program in execution is called a ____.', 'Programming', 'Process', 'High-level Language reading', 'Data releasing', 1, 'hardware', 0),
('For comparison and calculations, the computer uses ____.', 'CPU', 'ALU', 'Control Units', 'Processors', 1, 'hardware', 0),
('In a typical computer operation, which of the following memories is put in use?', 'ROM', 'HDD', 'CND', 'RAM', 3, 'hardware', 0),
('The basic goal of computer processors is to convert the given data into ____', 'Programs', 'Information', 'Contents of Main memory', 'Texts, Tables and Graphs', 1, 'hardware', 0),
('Which among the following is not a peripheral hardware device in a computer system?', 'Keyboard', 'Optical Drive', 'Printer', 'HDD', 3, 'hardware', 0),
('Computers process data under the control of sets of instructions called____.', 'Computer data', 'Computer programs', 'Computer buses', 'Computer instructions', 1, 'hardware', 0),
('What is the full form of CD-ROM?', 'Compact Disk Read Only Memory', 'Compact Disk Run Only Memory', 'Closed Disk Read Only Memory', 'Closed Disk Run Only Memory', 0, 'hardware', 0),
('What is the name of the software that allows us to browse through web pages called?', 'Mail Client', 'FTP Client', 'Messenger', 'Browser', 3, 'hardware', 0),
('What is BIOS battery?', 'This battery is used to change date/Time of system', 'This battery is used to change BIOS Configuration', 'A&B', 'None of these', 2, 'hardware', 0),
('A computer which links several PCs together in a network is called a', 'Minicomputer', 'Server', 'Client', 'Main Frame', 1, 'hardware', 0),
('NIC Stands for', 'Network Interface Card', 'Network Internal Card', 'Network Internet Client', 'Network Input Card', 0, 'hardware', 0),
('What is the complete name of UPS?', 'Unplugged Power Supply', 'Uninterruptible Power Supply', 'Unplugged Program Supply', 'Uninterruptible Plug Supply', 1, 'hardware', 0),
('The cabinet containing the computer’s working parts is known as the', 'workstation', 'system unit', 'local hard drive', 'none of the above', 1, 'hardware', 0),
('A Computer that is On the Network is a', 'Node', 'Terminal', 'Client', 'Online', 0, 'hardware', 0),
('Which of the following is not an output device?', 'Printer', 'Keyboard', 'Monitor', 'Speakers', 1, 'hardware', 0),
('Modem stands for', 'Monetary Demarkation', 'Monetary Devaluation Exchange Mechanism', 'Modulator Demodulater', 'Memory Demagnetization', 2, 'hardware', 0),
('Which of the following storage devices can store maximum amount of data?', 'Floppy Disk', 'Hard Disk', 'Compact Disk', 'Magneto Optic Disk', 1, 'hardware', 0),
('Windows Desktop contains which of the following:', 'start menu', 'All programs', 'taskbar', 'My Computer', 0, 'hardware', 0),
('Which of the following is not an operating system?', 'Windows', 'Linux', 'Oracle', 'DOS', 2, 'hardware', 0),
('What is the mean of the Rebooting in the operating system?', 'Restarting computer', 'Install the program', 'To scan', 'To turn off', 0, 'hardware', 0),
('When you delete a file in your computer, where does it go?', 'Recycle bin', 'Hard disk', 'Taskbar', 'None of these', 0, 'hardware', 0),
('Which of the following is not application software?', 'Windows 7', 'WordPad', 'Photoshop', 'MS-excel', 0, 'hardware', 0),
('What is Virtualization?', 'Creating physical environment on hardware side.', 'To create a virtual version of a device or resource, such as a server, storage device, network or even an operating system where the framework divides the resource into one or more execution environments.', 'Remote connection', 'To create logical connection with OS', 1, 'hardware', 0),
('What is a Virtual Machine?', 'Manufacture by Apple', 'A machine with virtualization software can host numerous applications, including those that run on different operating systems, on a single platform', 'One type of cloud application', 'None', 1, 'hardware', 0),
('Guest OS installed using _____', 'Virtualization Applications', 'VMWare', 'Virtual Box', 'Hyper-V', 1, 'hardware', 0);

-- N+ Questions
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('Which of the following transmission directions listed is not a legitimate channel?', 'Simplex', 'Half Duplex', 'Full Duplex', 'Double Duplex', 3, 'networking', 0),
('The location of a resource on the internet is given by its?', 'Protocol', 'URL', 'E-mail address', 'ICQ', 1, 'networking', 0),
('Communication between a computer and a keyboard involves transmission?', 'simplex', 'half-duplex', 'full-duplex', 'automatic', 0, 'networking', 0),
('A computer network permits sharing of', 'Resources', 'Information', 'Both a & b', 'None of these', 2, 'networking', 0),
('Transmission mode controls the direction of signal flow.', 'True', 'False', '', '', 0, 'networking', 0),
('A transmission mode that can transmit data in both the directions but transmits in only one direction at a time.', 'simplex', 'half duplex', 'full duplex', 'semi-duplex', 1, 'networking', 0),
('Telephone networks operate in this mode.', 'simplex', 'half duplex', 'full duplex', 'semi-duplex', 2, 'networking', 0),
('A walkie-talkie operates in ____________', 'simplex', 'half duplex', 'full duplex', 'semi-duplex', 1, 'networking', 0),
('The performance of data communications network depends on ..............', 'Number of users', 'The hardware and software', 'The transmission', 'All of the above', 3, 'networking', 0),
('What does LAN stand for?', 'Local Access Network', 'Local Area Network', 'Large Area Network', 'Local Application Network', 1, 'networking', 0),
('Which of the following is true about WAN?', 'Covers a small geographical area', 'Covers a large geographical area', 'Connects devices within a building', 'Typically used for personal devices', 1, 'networking', 0),
('What type of network is a MAN (Metropolitan Area Network)?', 'network confined to a single building', 'A network that connects multiple LANs across a city', 'A network that operates within a personal computer', 'A network that provides services within a neighborhood', 1, 'networking', 0),
('Which network type is best suited for connecting devices in a university campus?', 'LAN', 'WAN', 'MAN', 'CAN', 2, 'networking', 0),
('A SAN (Storage Area Network) is primarily used for what purpose?', 'To connect different offices across a city', 'To connect and provide access to storage devices', 'To share printers within a local area', 'To establish communication within a small office', 1, 'networking', 0),
('Which of the following is the primary characteristic of a LAN?', 'It spans multiple countries.', 'It uses satellite communication.', 'It covers a small, localized area.', 'It provides wireless communication over long distances.', 2, 'networking', 0),
('Which type of network is typically used to connect multiple branches of a company spread across different cities?', 'SAN', 'CAN', 'WAN', 'MAN', 2, 'networking', 0),
('A university''s entire campus, including multiple buildings, can be networked together using which type of network?', 'LAN', 'SAN', 'CAN', 'MAN', 3, 'networking', 0),
('What is the typical range of a MAN (Metropolitan Area Network)?', 'A few kilometers', 'Within a city', 'Nationwide', 'Global', 1, 'networking', 0),
('Which of the following is NOT an example of a wide area network (WAN)?', 'The Internet', 'A company’s network spanning multiple continents', 'A network covering a single office floor', 'A telecommunication network', 2, 'networking', 0),
('Which of the following is a type of network topology?', 'Star', 'Binary', 'Line', 'Square', 0, 'networking', 0),
('In a Bus topology, how are the devices connected?', 'In a ring-like structure', 'In a star-like arrangement', 'To a central cable or backbone', 'In a hierarchical structure', 2, 'networking', 0),
('Which network topology involves every device being connected to every other device?', 'Star', 'Mesh', 'Bus', 'Ring', 1, 'networking', 0),
('Which topology uses a central hub or switch to connect all devices?', 'Bus', 'Ring', 'Star', 'Tree', 2, 'networking', 0),
('In which topology do data packets travel in one direction, from one device to the next, until they reach their destination?', 'Bus', 'Ring', 'Mesh', 'Star', 1, 'networking', 0),
('Which of the following topologies is the most fault-tolerant?', 'Bus', 'Star', 'Ring', 'Mesh', 3, 'networking', 0),
('In a star topology, what happens if the central hub fails?', 'Only one connected device is affected.', 'The entire network fails.', 'The network performance improves.', 'The failure has no effect on the network.', 1, 'networking', 0),
('Which of the following is a disadvantage of a bus topology?', 'It is expensive to set up.', 'It is difficult to add new devices.', 'A failure in the central hub will cause the entire network to fail.', 'If the main cable fails, the entire network goes down.', 3, 'networking', 0),
('Which of the following topologies is typically used in Local Area Networks (LANs) for its simplicity and ease of troubleshooting?', 'Mesh topology', 'Bus topology', 'Ring topology', 'Star topology', 3, 'networking', 0),
('In a ring topology, what happens if a single device or connection fails?', 'The network continues to function normally.', 'The network splits into two smaller networks.', 'The entire network is disrupted.', 'Data will be automatically rerouted.', 2, 'networking', 0),
('Which topology has the advantage of easy installation and less cabling compared to a star topology?', 'Star topology', 'Bus topology', 'Ring topology', 'Mesh topology', 1, 'networking', 0),
('Which of the following is a primary advantage of the star topology?', 'Easy fault isolation', 'Less cabling required', 'Data collisions are frequent', 'Direct communication between devices', 0, 'networking', 0),
('Which topology is commonly used in wireless networks?', 'Mesh', 'Bus', 'Ring', 'Star', 0, 'networking', 0),
('Which of the following devices is used to connect multiple computers within a local area network (LAN)?', 'Modem', 'Switch', 'Router', 'Firewall', 1, 'networking', 0),
('Which network device is used to route data between different networks?', 'Hub', 'Switch', 'Router', 'Repeater', 2, 'networking', 0),
('What device is used to amplify or regenerate signals in a network to extend the transmission distance?', 'Switch', 'Router', 'Hub', 'Repeater', 3, 'networking', 0),
('Which device operates at the Data Link layer (Layer 2) of the OSI model to forward data packets between network segments?', 'Router', 'Switch', 'Modem', 'Firewall', 1, 'networking', 0),
('What is the primary function of a firewall in a network?', 'Amplify network signals', 'Filter incoming and outgoing network traffic', 'Convert analog signals to digital', 'Store data', 1, 'networking', 0),
('Which network device connects two dissimilar networks, such as a LAN to a WAN?', 'Bridge', 'Switch', 'Router', 'Modem', 2, 'networking', 0),
('Which device is typically used to connect devices within the same network, and does not analyze traffic or filter data packets?', 'Switch', 'Hub', 'Router', 'Firewall', 1, 'networking', 0),
('What is the purpose of a Network Interface Card (NIC)?', 'To convert digital signals into analog signals', 'To provide network access to a computer or device', 'To store data packets before transmission', 'To create network security policies', 1, 'networking', 0),
('Which of the following devices connects two or more networks and directs data between them using IP addresses?', 'Hub', 'Repeater', 'Router', 'Bridge', 2, 'networking', 0),
('Which network device is responsible for converting digital signals to analog signals and vice versa?', 'Switch', 'Router', 'Modem', 'Bridge', 2, 'networking', 0),
('Which device prevents unauthorized access to or from a private network?', 'Hub', 'Repeater', 'Firewall', 'Switch', 2, 'networking', 0),
('Which network device forwards data packets to all connected devices, regardless of the destination?', 'Switch', 'Router', 'Hub', 'Firewall', 2, 'networking', 0),
('What does an IP address stand for?', 'Internet Provider Address', 'Internal Protocol Address', 'Internet Protocol Address', 'International Provider Address', 2, 'networking', 0),
('Which of the following is a valid IPv4 address?', '192.168.1.1', '255.255.255.256', '10.0.0.0.1', '300.168.0.1', 0, 'networking', 0),
('How many bits are used in an IPv4 address?', '16 bits', '32 bits', '64 bits', '128 bits', 1, 'networking', 0),
('What is the maximum value of any octet in an IPv4 address?', '255', '256', '512', '1024', 0, 'networking', 0),
('Which of the following is a private IP address?', '8.8.8.8', '192.168.0.10', '172.32.0.1', '11.0.0.1', 1, 'networking', 0),
('What is the loopback IP address used for testing a network interface?', '127.0.0.1', '192.168.1.1', '255.255.255.0', '0.0.0.0', 0, 'networking', 0),
('How many bits are used in an IPv6 address?', '32 bits', '64 bits', '128 bits', '', 2, 'networking', 0),
('Which of the following is a valid IPv6 address?', '192.168.1.1', '2001:0db8:85a3:0000:0000:8a2e:0370:7334', '256.256.256.256', '10.0.0.0:255', 1, 'networking', 0),
('What is the default subnet mask for a Class C IPv4 address?', '255.0.0.0', '255.255.0.0', '255.255.255.0', '255.255.255.255', 2, 'networking', 0),
('Which class of IP addresses is used for multicast groups?', 'Class A', 'Class B', 'Class C', 'Class D', 3, 'networking', 0),
('Which protocol is used to assign IP addresses dynamically to devices on a network?', 'DNS', 'DHCP', 'FTP', 'HTTP', 1, 'networking', 0),
('What is the purpose of a subnet mask in an IP address?', 'To identify the class of the IP address', 'To route data between different networks', 'To define the network and host portions of an IP address', 'To encrypt the IP address', 2, 'networking', 0),
('Which of the following is not a reserved IP address range?', '10.0.0.0 – 10.255.255.255', '172.16.0.0 – 172.31.255.255', '192.168.0.0 – 192.168.255.255', '11.0.0.0 – 11.255.255.255', 3, 'networking', 0),
('What is the purpose of a default gateway in a network?', 'To assign IP addresses to devices', 'To encrypt data', 'To allow communication between devices in different networks', 'To provide DNS resolution', 2, 'networking', 0),
('Which organization is responsible for assigning public IP addresses?', 'IANA', 'ICANN', 'DHCP', 'W3C', 1, 'networking', 0),
('Which class of IP addresses allows for the largest number of hosts?', 'Class A', 'Class B', 'Class C', 'Class D', 0, 'networking', 0),
('What is a CIDR (Classless Inter-Domain Routing) notation used for?', 'To divide IP addresses into classes', 'To provide flexible allocation of IP addresses', 'To create a physical network', 'To assign MAC addresses', 1, 'networking', 0),
('What is the function of Network Address Translation (NAT)?', 'To assign public IP addresses to devices', 'To translate private IP addresses to a public IP address for Internet access', 'To resolve domain names to IP addresses', 'To dynamically assign IP addresses', 1, 'networking', 0),
('Which of the following addresses is used to broadcast a message to all devices in a network?', '0.0.0.0', '255.255.255.255', '127.0.0.1', '192.168.1.255', 1, 'networking', 0),
('OSI stands for __________', 'open system interconnection', 'operating system interface', 'optical service implementation', 'open service Internet', 0, 'networking', 0),
('The number of layers in ISO OSI reference model is __________', '4', '5', '6', '7', 3, 'networking', 0),
('Which address is used on the internet for employing the TCP/IP protocols?', 'physical address and logical address', 'port address', 'specific address', 'all of the mentioned', 3, 'networking', 0),
('Which layer is responsible for process-to-process delivery in a general network model?', 'network layer', 'transport layer', 'session layer', 'data link layer', 1, 'networking', 0),
('Which layer provides the services to user?', 'application layer', 'session layer', 'presentation layer', 'physical layer', 0, 'networking', 0),
('Transmission data rate is decided by ____________', 'network layer', 'physical layer', 'data link layer', 'transport layer', 1, 'networking', 0),
('The physical layer is concerned with ___________', 'bit-by-bit delivery', 'process to process delivery', 'application to application delivery', 'port to port delivery', 0, 'networking', 0),
('The physical layer translates logical communication requests from the ______ into hardware specific operations.', 'data link layer', 'network layer', 'transport layer', 'application layer', 0, 'networking', 0),
('The data link layer takes the packets from _________ and encapsulates them into frames for transmission.', 'network layer', 'physical layer', 'transport layer', 'application layer', 0, 'networking', 0),
('The network layer is concerned with __________ of data.', 'bits', 'frames', 'packets', 'bytes', 2, 'networking', 0),
('The network layer protocol for internet is __________', 'ethernet', 'internet protocol', 'hypertext transfer protocol', 'file transfer protocol', 1, 'networking', 0),
('Which of the following are transport layer protocols used in networking?', 'TCP and FTP', 'UDP and HTTP', 'TCP and UDP', 'HTTP and FTP', 2, 'networking', 0),
('Transmission control protocol ___________', 'is a connection-oriented protocol', 'uses a three-way handshake to establish a connection', 'receives data from application as a single stream', 'all of the mentioned', 3, 'networking', 0),
('Which protocol is connection-oriented?', 'UDP', 'TCP', 'ICMP', '', 1, 'networking', 0),
('Which protocol is generally faster due to its lack of error-checking and minimal overhead?', 'TCP', 'HTTP', 'UDP', 'FTP', 2, 'networking', 0),
('What is the main purpose of the TCP three-way handshake?', 'To verify data packets are error-free', 'To establish a reliable connection between client and server', 'To exchange encryption keys', 'To disconnect the client and server', 1, 'networking', 0),
('Which protocol is most commonly used for real-time applications like live video streaming?', 'TCP', 'UDP', 'HTTP', 'SMTP', 1, 'networking', 0),
('Which of the following is true about TCP but NOT true about UDP?', 'It is faster', 'It guarantees packet delivery', 'It is used for streaming services', 'It has no error-checking', 1, 'networking', 0),
('In which layer of the OSI model do TCP and UDP operate?', 'Network layer', 'Data link layer', 'Transport layer', 'Application layer', 2, 'networking', 0),
('Which protocol is more suitable for transferring large files over a network where reliability is crucial?', 'UDP', 'ICMP', 'HTTP', 'TCP', 3, 'networking', 0),
('Which protocol will retry sending data packets if they are lost during transmission?', 'UDP', 'IP', 'ICMP', 'TCP', 3, 'networking', 0),
('In which scenario would you most likely use UDP over TCP?', 'File download', 'Online gaming', 'Web browsing', 'Email communication', 1, 'networking', 0),
('Which protocol has a higher overhead due to connection establishment and error-checking features?', 'UDP', 'TCP', 'IP', 'ICMP', 1, 'networking', 0),
('Which of the following is a unique characteristic of UDP?', 'Guarantees data delivery', 'Uses a connection-oriented model', 'Does not require a connection setup', 'Provides packet sequencing', 2, 'networking', 0),
('Which port is commonly used by HTTP?', '20', '21', '80', '443', 2, 'networking', 0),
('What port does HTTPS typically use?', '21', '80', '110', '443', 3, 'networking', 0),
('Which port is used by FTP (File Transfer Protocol) for data transfer?', '20', '22', '25', '53', 0, 'networking', 0),
('Port 22 is commonly associated with which protocol?', 'SMTP', 'Telnet', 'SSH', 'DNS', 2, 'networking', 0),
('Which protocol commonly uses port 25?', 'DNS', 'SMTP', 'POP3', 'IMAP', 1, 'networking', 0),
('Which port does the DNS (Domain Name System) use?', '53', '80', '110', '443', 0, 'networking', 0),
('What port does Telnet typically use?', '22', '23', '25', '44', 1, 'networking', 0),
('Which of the following device is a data link layer device?', 'Router', 'Switch', 'Hub', 'Repeater', 1, 'networking', 0),
('HTTP is ________ protocol.', 'application layer', 'transport layer', 'network layer', 'data link layer', 0, 'networking', 0),
('HTTP client requests by establishing a __________ connection to a particular port on the server.', 'User datagram protocol', 'Transmission control protocol', 'Border gateway protocol', 'Domain host control protocol', 1, 'networking', 0),
('FTP server listens for connection on which port number?', '20', '21', '22', '23', 1, 'networking', 0),
('Network layer firewall has two sub-categories as _________', 'State full firewall and stateless firewall', 'Bit oriented firewall and byte-oriented firewall', 'Frame firewall and packet firewall', 'Network layer firewall and session layer firewall', 0, 'networking', 0),
('A proxy firewall filters at _________', 'Physical layer', 'Data link layer', 'Network layer', 'Application layer', 3, 'networking', 0),
('A packet filter firewall filters at __________', 'Physical layer', 'Data link layer', 'Network layer or Transport layer', 'Application layer', 2, 'networking', 0),
('DHCP (dynamic host configuration protocol) provides __________ to the client.', 'IP address', 'MAC address', 'Url', 'None of the mentioned', 0, 'networking', 0),
('DHCP is used for ________', 'IPv6', 'IPv4', 'Both IPv6 and IPv4', 'None of the mentioned', 2, 'networking', 0),
('The DHCP server _________', 'maintains a database of available IP addresses', 'maintains the information about client configuration parameters', 'grants a IP address when receives a request from a client', 'all of the mentioned', 3, 'networking', 0),
('IP assigned for a client by DHCP server is', 'for a limited period', 'for an unlimited period', 'not time dependent', 'none of the mentioned', 0, 'networking', 0);

-- CCNA questions
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('___________ command is used to enter privileged mode in a switch.', 'enable', 'configure terminal', 'hostname', 'wr', 0, 'ccna', 0),
('Which command is used to configure telnet for remote access?', 'enable', 'login', 'line vty 0 4', 'interface fastEthernet 0/1', 2, 'ccna', 0),
('Command to create a VLAN in a switch?', 'vlan', 'name HR', 'interface vlan', 'no vlan', 0, 'ccna', 0),
('Which command is used to check whether the trunking is configured or not?', 'switchport mode trunk', 'switchport mode access', 'show interface trunk', 'show running configuration', 2, 'ccna', 0),
('Switch CLI is used to configure routing protocols.', 'True', 'False', '', '', 1, 'ccna', 0),
('How to enable different ports to access a VLAN?', 'switchport access vlan', 'switchport mode access', 'interface vlan', 'switchport mode trunk', 0, 'ccna', 0),
('The switch requires an IP address for each port in use.', 'True', 'False', '', '', 1, 'ccna', 0),
('Which of the following device is a data link layer device?', 'Router', 'Switch', 'Hub', 'Repeater', 1, 'ccna', 0),
('_______ allows you to connect and login to a remote computer', 'Telnet', 'FTP', 'HTTP', 'SMTP', 0, 'ccna', 0),
('Telnet is used for _______', 'Television on net', 'Network of Telephones', 'Remote Login', 'Teleshopping site', 2, 'ccna', 0),
('Which one of the following is not correct?', 'telnet is a general-purpose client-server program', 'telnet lets user access an application on a remote computer', 'telnet can also be used for file transfer', 'telnet can be used for remote login', 2, 'ccna', 0),
('HTTP is ________ protocol.', 'application layer', 'transport layer', 'network layer', 'data link layer', 0, 'ccna', 0),
('HTTP client requests by establishing a __________ connection to a particular port on the server.', 'User datagram protocol', 'Transmission control protocol', 'Border gateway protocol', 'Domain host control protocol', 1, 'ccna', 0),
('FTP server listens for connection on which port number?', '20', '21', '22', '23', 1, 'ccna', 0),
('Secure shell (SSH) network protocol is used for __________', 'secure data communication', 'remote command-line login', 'remote command execution', 'all of the mentioned', 3, 'ccna', 0),
('SSH uses ___________ to authenticate the remote computer.', 'public-key cryptography', 'private-key cryptography', 'any of public-key or private-key', 'both public-key & private-key', 0, 'ccna', 0),
('Which standard TCP port is assigned for contacting SSH servers?', 'port 21', 'port 22', 'port 23', 'port 24', 1, 'ccna', 0),
('Which of the following can be suited as a definition of an Access List?', 'Set of protocols to define traffic in a router', 'Set of rules used for packet filtering', 'Set of guidelines that every router should follow', 'Set of features that every router contains', 1, 'ccna', 0),
('Which set of things will be taken into account in order to filter the packets in an extended access list?', 'Source IP address and destination IP address', 'Source IP address, protocol and port number', 'Source IP address', 'Source IP address, protocol, port number and destination IP address', 3, 'ccna', 0),
('One interface of a router can have multiple access lists.', 'True', 'False', '', '', 1, 'ccna', 0);
